var emissionEuropa:number =4209.3;
var emissionAsia:number =16274.1;  
var emissionAfrica:number =1235.5;
var emissionSouthAmerica:number =1262.5;
var emissionNorthAmerica:number =6035.6; 
var emissionAustralia:number =2100.5;
var emissionWorld: number = emissionAsia + emissionAustralia + emissionNorthAmerica + emissionSouthAmerica + emissionAfrica + emissionEuropa;
var relativEmissionEurop: number = emissionEuropa / emissionWorld ; 
var EmissionEuropa2008: number = 4965.7;
var EmissionEuropadifference: number = emissionEuropa - EmissionEuropa2008 ; 
var EmissionEruopaProzent: number = EmissionEuropadifference / EmissionEuropa2008 ;
var emissionMinusEurop: number = emissionEuropa - EmissionEuropa2008; 
var relativEmissionAsien: number = emissionAsia / emissionWorld; 
var EmissionAsia2008: number = 12954.7; 
var EmissionAsiadifference: number = emissionAsia - EmissionAsia2008 ; 
var EmissionAsiaProzent: number = EmissionAsiadifference / EmissionAsia2008 ; 
var emissionMinusAsia: number = emissionAsia - EmissionAsia2008;  
var relativEmissionAfrica: number = emissionAfrica / emissionWorld; 
var EmissionAfrica2008: number = 1028; 
var EmissionAfricadifference: number = emissionAfrica - EmissionAfrica2008; 
var EmissionAfricaProzent: number = EmissionAfricadifference / EmissionAfrica2008; 
var emissionMinusAfrica: number = emissionAfrica - EmissionAfrica2008; 
var relativEmissionSouthAmerica: number = emissionSouthAmerica/ emissionWorld; 
var EmissionSouthAmerica2008: number = 1132.6; 
var EmissionSouthAmericadifference: number = emissionSouthAmerica - EmissionSouthAmerica2008; 
var EmissionSouthAmericaProzent: number = EmissionSouthAmericadifference / EmissionSouthAmerica2008 ; 
var emissionMinusSouthAmerica: number = emissionSouthAmerica - EmissionSouthAmerica2008; 
var relativEmissionNorthAmerica: number = emissionNorthAmerica/ emissionWorld; 
var EmissionNorthAmerica2008: number = 6600.4; 
var EmissionNorthAmericadifference: number =  -emissionNorthAmerica - EmissionNorthAmerica2008; 
var EmissionNorthAmericaProzent: number = EmissionNorthAmericadifference / EmissionNorthAmerica2008 ; 
var emissionMinusNorthAmerica: number = emissionNorthAmerica - EmissionNorthAmerica2008; 
var relativEmissionAustralia: number = emissionAustralia/ emissionWorld; 
var EmissionAustralia2008: number = 1993; 
var EmissionAustraliadifference: number = emissionAustralia - EmissionAustralia2008; 
var EmissionAustraliaProzent: number = EmissionAustraliadifference / EmissionAustralia2008 ; 
var emissionMinusAustralia: number = emissionAustralia - EmissionAustralia2008; 



console.log("Die Emission von Europa beträgt: " + emissionEuropa + " kgCO2");
console.log("Relativ zur Gesamtemission der Welt verursacht Europa damit "  + relativEmissionEurop * 100+ " %");
console.log("In Europa hat sich die Emission zwischen 2008 und 2018 um " + EmissionEruopaProzent * 100 + " % verändert");
console.log("Im Vergleich von 2018 zu 2008 sind das " + emissionMinusEurop + " kgCO2");
console.log("Die Emission von Asien beträgt:" + emissionAsia + "kgCO2");
console.log("Relativ zur Gesamtemission der Welt verursacht Asien damit "  + relativEmissionAsien * 100 + " %");
console.log("In Asien hat sich die Emission zwischen 2008 und 2018 um " + EmissionAsiaProzent * 100 + " % verändert");
console.log("Im Vergleich von 2018 zu 2008 sind das " + emissionMinusAsia + " kgCO2");
console.log("Die Emission von Afrika ist:" + emissionAfrica + "kgCO2");
console.log("Relativ zur Gesamtemission der Welt verursacht Afrika damit "  + relativEmissionAfrica *100+ " %");
console.log("In Afrika hat sich die Emission zwischen 2008 und 2018 um " + EmissionAfricaProzent *100+ " % verändert");
console.log("Im Vergleich von 2018 zu 2008 sind das " + emissionMinusAfrica + " kgCO2");
console.log("Die Emission von Süd-Amerika ist:" + emissionSouthAmerica + "kgCO2"); 
console.log("Relativ zur Gesamtemission der Welt verursacht Süd-Amerika damit "  + relativEmissionSouthAmerica *100 + " %");
console.log("In Süd-Amerika hat sich die Emission zwischen 2008 und 2018 um " + EmissionSouthAmericaProzent *100 + " % verändert");
console.log("Im Vergleich von 2018 zu 2008 sind das " + emissionMinusSouthAmerica + " kgCO2");
console.log("Die Emission von Nord-Amerika ist: " + emissionNorthAmerica + "kgCO2"); 
console.log("Relativ zur Gesamtemission der Welt verursacht Nord-Amerika damit "  + relativEmissionNorthAmerica *100 + " %");
console.log("In Nord-Amerika hat sich die Emission zwischen 2008 und 2018 um " + EmissionNorthAmericaProzent *100 + " % verändert");
console.log("Im Vergleich von 2018 zu 2008 sind das " + emissionMinusNorthAmerica + " kgCO2");
console.log("Die Emission von Australien ist: " + emissionAustralia + " kgCO2"); 
console.log("Relativ zur Gesamtemission der Welt verursacht Australien damit "  + relativEmissionAustralia *100 + " %");
console.log("In Australien hat sich die Emission zwischen 2008 und 2018 um " + EmissionAustraliaProzent *100 + " % verändert");
console.log("Im Vergleich von 2018 zu 2008 sind das " + emissionMinusAustralia + " kgCO2");