var emissionEuropa = 4209.3;
var emissionAsia = 16274.1;
var emissionAfrica = 1235.5;
var emissionSouthAmerica = 1262.5;
var emissionNorthAmerica = 6035.6;
var emissionAustralia = 2100.5;
var emissionWorld = emissionAsia + emissionAustralia + emissionNorthAmerica + emissionSouthAmerica + emissionAfrica + emissionEuropa;
var relativEmissionEurop = emissionEuropa / emissionWorld;
var EmissionEuropa2008 = 4965.7;
var EmissionEuropadifference = emissionEuropa - EmissionEuropa2008;
var EmissionEruopaProzent = EmissionEuropadifference / EmissionEuropa2008;
var emissionMinusEurop = emissionEuropa - EmissionEuropa2008;
var relativEmissionAsien = emissionAsia / emissionWorld;
var EmissionAsia2008 = 12954.7;
var EmissionAsiadifference = emissionAsia - EmissionAsia2008;
var EmissionAsiaProzent = EmissionAsiadifference / EmissionAsia2008;
var emissionMinusAsia = emissionAsia - EmissionAsia2008;
var relativEmissionAfrica = emissionAfrica / emissionWorld;
var EmissionAfrica2008 = 1028;
var EmissionAfricadifference = emissionAfrica - EmissionAfrica2008;
var EmissionAfricaProzent = EmissionAfricadifference / EmissionAfrica2008;
var emissionMinusAfrica = emissionAfrica - EmissionAfrica2008;
var relativEmissionSouthAmerica = emissionSouthAmerica / emissionWorld;
var EmissionSouthAmerica2008 = 1132.6;
var EmissionSouthAmericadifference = emissionSouthAmerica - EmissionSouthAmerica2008;
var EmissionSouthAmericaProzent = EmissionSouthAmericadifference / EmissionSouthAmerica2008;
var emissionMinusSouthAmerica = emissionSouthAmerica - EmissionSouthAmerica2008;
var relativEmissionNorthAmerica = emissionNorthAmerica / emissionWorld;
var EmissionNorthAmerica2008 = 6600.4;
var EmissionNorthAmericadifference = -emissionNorthAmerica - EmissionNorthAmerica2008;
var EmissionNorthAmericaProzent = EmissionNorthAmericadifference / EmissionNorthAmerica2008;
var emissionMinusNorthAmerica = emissionNorthAmerica - EmissionNorthAmerica2008;
var relativEmissionAustralia = emissionAustralia / emissionWorld;
var EmissionAustralia2008 = 1993;
var EmissionAustraliadifference = emissionAustralia - EmissionAustralia2008;
var EmissionAustraliaProzent = EmissionAustraliadifference / EmissionAustralia2008;
var emissionMinusAustralia = emissionAustralia - EmissionAustralia2008;
console.log("Die Emission von Europa beträgt: " + emissionEuropa + " kgCO2");
console.log("Relativ zur Gesamtemission der Welt verursacht Europa damit " + relativEmissionEurop * 100 + " %");
console.log("In Europa hat sich die Emission zwischen 2008 und 2018 um " + EmissionEruopaProzent * 100 + " % verändert");
console.log("Im Vergleich von 2018 zu 2008 sind das " + emissionMinusEurop + " kgCO2");
console.log("Die Emission von Asien beträgt:" + emissionAsia + "kgCO2");
console.log("Relativ zur Gesamtemission der Welt verursacht Asien damit " + relativEmissionAsien * 100 + " %");
console.log("In Asien hat sich die Emission zwischen 2008 und 2018 um " + EmissionAsiaProzent * 100 + " % verändert");
console.log("Im Vergleich von 2018 zu 2008 sind das " + emissionMinusAsia + " kgCO2");
console.log("Die Emission von Afrika ist:" + emissionAfrica + "kgCO2");
console.log("Relativ zur Gesamtemission der Welt verursacht Afrika damit " + relativEmissionAfrica * 100 + " %");
console.log("In Afrika hat sich die Emission zwischen 2008 und 2018 um " + EmissionAfricaProzent * 100 + " % verändert");
console.log("Im Vergleich von 2018 zu 2008 sind das " + emissionMinusAfrica + " kgCO2");
console.log("Die Emission von Süd-Amerika ist:" + emissionSouthAmerica + "kgCO2");
console.log("Relativ zur Gesamtemission der Welt verursacht Süd-Amerika damit " + relativEmissionSouthAmerica * 100 + " %");
console.log("In Süd-Amerika hat sich die Emission zwischen 2008 und 2018 um " + EmissionSouthAmericaProzent * 100 + " % verändert");
console.log("Im Vergleich von 2018 zu 2008 sind das " + emissionMinusSouthAmerica + " kgCO2");
console.log("Die Emission von Nord-Amerika ist: " + emissionNorthAmerica + "kgCO2");
console.log("Relativ zur Gesamtemission der Welt verursacht Nord-Amerika damit " + relativEmissionNorthAmerica * 100 + " %");
console.log("In Nord-Amerika hat sich die Emission zwischen 2008 und 2018 um " + EmissionNorthAmericaProzent * 100 + " % verändert");
console.log("Im Vergleich von 2018 zu 2008 sind das " + emissionMinusNorthAmerica + " kgCO2");
console.log("Die Emission von Australien ist: " + emissionAustralia + " kgCO2");
console.log("Relativ zur Gesamtemission der Welt verursacht Australien damit " + relativEmissionAustralia * 100 + " %");
console.log("In Australien hat sich die Emission zwischen 2008 und 2018 um " + EmissionAustraliaProzent * 100 + " % verändert");
console.log("Im Vergleich von 2018 zu 2008 sind das " + emissionMinusAustralia + " kgCO2");
//# sourceMappingURL=script.js.map